    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: yolo-client
      name: yolo-client-deployment
      namespace: default
    spec:
      selector:
        matchLabels:
          app: yolo-client
      replicas: 1
      template:
        metadata:
          labels:
            app: yolo-client
        spec:
          containers:
          - name: yolo-client
            image: albert1993/yolo_app:v1.0.0
            ports:
            - containerPort: 3000
            imagePullPolicy: Always
            resources:
              requests:
                memory: "400Mi"
                cpu: "400m"
              limits:
                memory: "1Gi"
                cpu: "1"
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 3000
              initialDelaySeconds: 180 
              periodSeconds: 10 
              timeoutSeconds: 3
              failureThreshold: 3 
              successThreshold: 1 
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 3000
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 3
              successThreshold: 1
            volumeMounts:
            - mountPath: "/tmp"
              name: yolo-client
          volumes:
          - name: yolo-client
            persistentVolumeClaim:
              claimName: pvc-default