version: '3'

services:  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    environment:
      MONGO:URL: mongodb+srv://albert:dLQc2XoBxRCCOwRD@cluster0.zgz8m.mongodb.net/yolomy      
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
   
  mongo:
    image: mongo
    ports: 
      - "9000:9000"  
    networks:
      - ecommerce-network
    volumes:
      - mongo-data:/data/db      

volumes:
  mongo-data:
networks:
  ecommerce-network:   