    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: backend-app
      name: backend-app-deployment
      namespace: default
    spec:
      selector:
        matchLabels:
          app: backend-app
      replicas: 1
      template:
        metadata:
          labels:
            app: backend-app
        spec:
          containers:
          - name: backend-app
            image: albert1993/yolo_backend:v1.0.0
            ports:
            - containerPort: 5000
            imagePullPolicy: Always
            resources:
              requests:
                memory: "400Mi"
                cpu: "400m"
              limits:
                memory: "1Gi"
                cpu: "1"
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 5000
              initialDelaySeconds: 180
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 3 
              successThreshold: 1
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 5000
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 3
              successThreshold: 1 
            volumeMounts:
            - mountPath: "/tmp"
              name: backend-app
          volumes:
          - name: backend-app
            persistentVolumeClaim:
              claimName: pvc-default
                